### ISSUE TITLE
What's performance of  the SemEval-2018's winner model GIST in the adversarial dataset?

### ISSUE THREAD

**Issue by fancyerii** [IKMLab/arct2#2]
I think ACRT dataset don't contain the world knowledge to solve the problem. And it seems BERT can't learn this world knowledge from huge unsupervised data. But the GIST use SNLI and MultiNLI dataset to learn ESIM. So GIST may learn the world knowledge for logic inference task. Have you tested GIST model in the adversarial dataset? If it's as bad as BERT, we can conclude that it also learned bad statistical cues. But if not, we should use these dataset to "pretraining" BERT and then training it in ACRT adversarial dataset.

**Comment by timniven** [comment]
Hi fancyerii, thanks for your feedback. I personally don't see any strong reason to suppose that NLI data would teach any of the world knowledge required for this task. I do not plan to conduct this experiment since I personally guess the chance of it succeeding is very low. You are welcome to try it, though, and let me know how it goes if you do!

Kind regards :)

Tim
